# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 576d217abdcfdccd89c31ee7bb850ee80553bc16f785c592c3dea87dcc8348a139ffed9aa7c34e4640e5ef965dd06469ce3541e86c83be1141dcee4f355d81a7

test:
  secret_key_base: 41290d13ab12cbcaa496dbcc55e74cff0cd1380ee9cfbb87348917a37a84aef281aba6e61f0333afb41acfabe024889824d18bd08ea955ae63101f9435d83a5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
